name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: make test-server-cov
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

